# Generated by Django 5.0.4 on 2024-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFlashpointRisk',
            fields=[
                ('EVENT_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('EVENT_YYYYMMDD', models.DateField()),
                ('EVENT_YYYYMM', models.IntegerField()),
                ('EVENT_YYYY', models.IntegerField()),
                ('EVENT_YYYYFFFF', models.FloatField()),
                ('INITIATOR_CODE', models.CharField(max_length=10)),
                ('INITIATOR_NAME', models.CharField(max_length=255)),
                ('INITIATOR_COUNTRY_CODE', models.CharField(max_length=10)),
                ('INITIATOR_KNOWN_GROUP_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_ETHNIC_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_RELIGION1_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_RELIGION2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_TYPE1_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_TYPE2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_TYPE3_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_CODE', models.CharField(max_length=10)),
                ('TARGET_NAME', models.CharField(max_length=255)),
                ('TARGET_COUNTRY_CODE', models.CharField(max_length=10)),
                ('TARGET_KNOWN_GROUP_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_ETHNIC_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_RELIGION1_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_RELIGION2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_TYPE1_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_TYPE2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_TYPE3_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('IS_EVENT_ORIGIN', models.BooleanField()),
                ('EVENT_CODE', models.CharField(max_length=10)),
                ('EVENT_BASE_CODE', models.CharField(max_length=10)),
                ('EVENT_ORIGIN_CODE', models.CharField(max_length=10)),
                ('EVENT_CLASSIFICATION', models.IntegerField()),
                ('STABILITY_SCALE', models.FloatField()),
                ('EVENT_MENTION_COUNT', models.IntegerField()),
                ('EVENT_MENTION_SOURCES_COUNT_LAST15MINUTES', models.IntegerField(blank=True, null=True)),
                ('EVENT_MENTION_ARTICLES_COUNT_LAST15MINUTES', models.IntegerField(blank=True, null=True)),
                ('EVENT_AVG_TONE_SOURCES_LAST15MINUTES', models.FloatField()),
                ('INITIATOR_GEO_TYPE', models.IntegerField()),
                ('INITIATOR_GEO_FULLNAME', models.CharField(max_length=255)),
                ('INITIATOR_GEO_COUNTRY_CODE', models.CharField(max_length=10)),
                ('INITIATOR_GEO_ADM1_CODE', models.CharField(max_length=10)),
                ('INITIATOR_GEO_ADM2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('INITIATOR_GEO_LATITUDE', models.FloatField()),
                ('INITIATOR_GEO_LONGITUDE', models.FloatField()),
                ('INITIATOR_GEO_FEATURE_ID', models.CharField(max_length=20)),
                ('TARGET_GEO_TYPE', models.IntegerField()),
                ('TARGET_GEO_FULLNAME', models.CharField(max_length=255)),
                ('TARGET_GEO_COUNTRY_CODE', models.CharField(max_length=10)),
                ('TARGET_GEO_ADM1_CODE', models.CharField(max_length=10)),
                ('TARGET_GEO_ADM2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('TARGET_GEO_LATITUDE', models.FloatField()),
                ('TARGET_GEO_LONGITUDE', models.FloatField()),
                ('TARGET_GEO_FEATURE_ID', models.CharField(max_length=20)),
                ('FLASHPOINT_GEO_TYPE', models.IntegerField()),
                ('FLASHPOINT_GEO_FULLNAME', models.CharField(max_length=255)),
                ('FLASHPOINT_GEO_COUNTRY_CODE', models.CharField(max_length=10)),
                ('FLASHPOINT_GEO_ADM1_CODE', models.CharField(max_length=10)),
                ('FLASHPOINT_GEO_ADM2_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('FLASHPOINT_GEO_LATITUDE', models.FloatField()),
                ('FLASHPOINT_GEO_LONGITUDE', models.FloatField()),
                ('FLASHPOINT_GEO_FEATURE_ID', models.CharField(max_length=20)),
                ('DATEADDED', models.DateField()),
                ('SOURCEURL', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['EVENT_YYYYMMDD'], name='events_data_EVENT_Y_7d2f1b_idx'), models.Index(fields=['EVENT_YYYYMM'], name='events_data_EVENT_Y_0cbdee_idx'), models.Index(fields=['EVENT_YYYY'], name='events_data_EVENT_Y_d67576_idx'), models.Index(fields=['INITIATOR_CODE'], name='events_data_INITIAT_1d3b09_idx'), models.Index(fields=['TARGET_CODE'], name='events_data_TARGET__1fc66b_idx'), models.Index(fields=['INITIATOR_COUNTRY_CODE'], name='events_data_INITIAT_7afd79_idx'), models.Index(fields=['TARGET_COUNTRY_CODE'], name='events_data_TARGET__3b1002_idx'), models.Index(fields=['EVENT_CODE'], name='events_data_EVENT_C_9fbc64_idx'), models.Index(fields=['INITIATOR_GEO_LATITUDE', 'INITIATOR_GEO_LONGITUDE'], name='events_data_INITIAT_8a016f_idx'), models.Index(fields=['TARGET_GEO_LATITUDE', 'TARGET_GEO_LONGITUDE'], name='events_data_TARGET__b4ab1a_idx'), models.Index(fields=['FLASHPOINT_GEO_LATITUDE', 'FLASHPOINT_GEO_LONGITUDE'], name='events_data_FLASHPO_d54e0d_idx')],
            },
        ),
    ]
