# Generated by Django 5.0.4 on 2024-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['EVENT_YYYYMMDD'], name='events_data_EVENT_Y_7d2f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['EVENT_YYYYMM'], name='events_data_EVENT_Y_0cbdee_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['EVENT_YYYY'], name='events_data_EVENT_Y_d67576_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['INITIATOR_CODE'], name='events_data_INITIAT_1d3b09_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['TARGET_CODE'], name='events_data_TARGET__1fc66b_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['INITIATOR_COUNTRY_CODE'], name='events_data_INITIAT_7afd79_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['TARGET_COUNTRY_CODE'], name='events_data_TARGET__3b1002_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['EVENT_CODE'], name='events_data_EVENT_C_9fbc64_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['INITIATOR_GEO_LATITUDE', 'INITIATOR_GEO_LONGITUDE'], name='events_data_INITIAT_8a016f_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['TARGET_GEO_LATITUDE', 'TARGET_GEO_LONGITUDE'], name='events_data_TARGET__b4ab1a_idx'),
        ),
        migrations.AddIndex(
            model_name='geoflashpointrisk',
            index=models.Index(fields=['FLASHPOINT_GEO_LATITUDE', 'FLASHPOINT_GEO_LONGITUDE'], name='events_data_FLASHPO_d54e0d_idx'),
        ),
    ]
