CREATE TABLE GEO_FLASHPOINT_RISKS (
    EVENT_ID BIGINT PRIMARY KEY,
    EVENT_YYYYMMDD DATE,
    EVENT_YYYYMM INTEGER,
    EVENT_YYYY INTEGER,
    EVENT_YYYYFFFF FLOAT,
    INITIATOR_CODE VARCHAR(10),
    INITIATOR_NAME VARCHAR(255),
    INITIATOR_COUNTRY_CODE VARCHAR(10),
    INITIATOR_KNOWN_GROUP_CODE VARCHAR(10),
    INITIATOR_ETHNIC_CODE VARCHAR(10),
    INITIATOR_RELIGION1_CODE VARCHAR(10),
    INITIATOR_RELIGION2_CODE VARCHAR(10),
    INITIATOR_TYPE1_CODE VARCHAR(10),
    INITIATOR_TYPE2_CODE VARCHAR(10),
    INITIATOR_TYPE3_CODE VARCHAR(10),
    TARGET_CODE VARCHAR(10),
    TARGET_NAME VARCHAR(255),
    TARGET_COUNTRY_CODE VARCHAR(10),
    TARGET_KNOWN_GROUP_CODE VARCHAR(10),
    TARGET_ETHNIC_CODE VARCHAR(10),
    TARGET_RELIGION1_CODE VARCHAR(10),
    TARGET_RELIGION2_CODE VARCHAR(10),
    TARGET_TYPE_CODE VARCHAR(10),
    TARGET_TYPE2_CODE VARCHAR(10),
    TARGET_TYPE3_CODE VARCHAR(10),
    IS_EVENT_ORIGIN BOOLEAN,
    EVENT_CODE VARCHAR(10),
    EVENT_BASE_CODE VARCHAR(10),
    EVENT_ORIGIN_CODE VARCHAR(10),
    EVENT_CLASSIFICATION INTEGER, -- Verbal Cooperation (1), Material Cooperation (2), Verbal Conflict (3), Material Conflict (4)
    STABILITY_SCALE FLOAT, -- Goldstein Scale
    EVENT_MENTION_COUNT INTEGER,
    EVENT_MENTION_SOURCES_COUNT_LAST15MINUTES INTEGER,
    EVENT_MENTION_ARTICLES_COUNT_LAST15MINUTES INTEGER,
    EVENT_AVG_TONE_SOURCES_LAST15MINUTES FLOAT, -- -100 (extremely negative) to +100 (extremely positive), commonly -10 to +10 0 being neutral
    INITIATOR_GEO_TYPE INTEGER, -- Country (1), US State (2), US City (3), World City (int'l city) (4), World state (int'l state) (5)
    INITIATOR_GEO_FULLNAME VARCHAR(255),
    INITIATOR_GEO_COUNTRY_CODE VARCHAR(10),
    INITIATOR_GEO_ADM1_CODE VARCHAR(10),
    INITIATOR_GEO_ADM2_CODE VARCHAR(10),
    INITIATOR_GEO_LATITUDE FLOAT,
    INITIATOR_GEO_LONGITUDE FLOAT,
    INITIATOR_GEO_FEATURE_ID VARCHAR(20),
    TARGET_GEO_TYPE INTEGER,
    TARGET_GEO_FULLNAME, VARCHAR(255),
    TARGET_GEO_COUNTRY_CODE VARCHAR(10),
    TARGET_GEO_ADM1_CODE VARCHAR(10),
    TARGET_GEO_ADM2_CODE VARCHAR(10),
    TARGET_GEO_LATITUDE FLOAT,
    TARGET_GEO_LONGITUDE FLOAT,
    TARGET_GEO_FEATURE_ID VARCHAR(20),
    FLASHPOINT_GEO_TYPE INTEGER,
    FLASHPOINT_GEO_FULLNAME VARCHAR(255),
    FLASHPOINT_GEO_COUNTRY_CODE VARCHAR(10),
    FLASHPOINT_GEO_ADM1_CODE VARCHAR(10),
    FLASHPOINT_GEO_ADM2_CODE VARCHAR(10),
    FLASHPOINT_GEO_LATITUDE FLOAT,
    FLASHPOINT_GEO_LONGITUDE FLOAT,
    FLASHPOINT_GEO_FEATURE_ID VARCHAR(20),
    DATEADDED DATE,
    SOURCEURL TEXT
);
-- Indexes for improved performance on frequently queried fields
CREATE INDEX idx_event_date ON GEO_FLASHPOINT_RISKS (EVENT_YYYYMMDD);
CREATE INDEX idx_month_year ON GEO_FLASHPOINT_RISKS (EVENT_YYYYMM);
CREATE INDEX idx_year ON GEO_FLASHPOINT_RISKS (EVENT_YYYY);
CREATE INDEX idx_initiator_code ON GEO_FLASHPOINT_RISKS (INITIATOR_CODE);
CREATE INDEX idx_target_code ON GEO_FLASHPOINT_RISKS (TARGET_CODE);
CREATE INDEX idx_flashpoint_geo_type ON GEO_FLASHPOINT_RISKS (FLASHPOINT_GEO_TYPE);
